=== City-of-Helsinki/ya-integration/src/main/resources/schema/kipa/json_schema_MYK_HKK.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "delivery": {
      "type": "object",
      "properties": {
        "fileName": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "minimum": 0
        },
        "sentAt": {
          "type": "string",
          "format": "date"
        },
        "from": {
          "type": "string",
          "maxLength": 2
        },
        "to": {
          "type": "string"
        }
      },
      "required": ["fileName", "id", "sentAt", "from", "to"]
    },
    "bizTalkPipe": {
      "type": "string"
    },
    "invoiceNumber": {
      "type": "integer",
      "minimum": 0
    },
    "refundedInvoiceNumber": {
      "type": ["integer", "null"]
    },
    "invoiceDate": {
      "type": "string",
      "format": "date"
    },
    "dueDate": {
      "type": "string",
      "format": "date"
    },
    "receiptDate": {
      "type": "string",
      "format": "date"
    },
    "grossSum": {
      "type": "number",
      "minimum": 0
    },
    "currency": {
      "type": "string",
      "maxLength": 3
    },
    "ourReference": {
      "type": "string"
    },
    "customerBankReference": {
      "type": ["string", "null"]
    },
    "periodStartDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "periodEndDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "paymentPeriodStartDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "paymentPeriodEndDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "employeeName": {
      "type": ["string", "null"]
    },
    "customProjectCode": {
      "type": ["string", "null"]
    },
    "receiver": {
      "type": "object",
      "properties": {
        "profitCenterCode": {
          "type": ["integer", "null"]
        },
        "bankAccount": {
          "type": "object",
          "properties": {
            "value": {
              "type": "string",
              "maxLength": 34
            },
            "bicCode": {
              "type": "string",
              "maxLength": 11
            }
          },
          "required": ["value", "bicCode"]
        },
        "name": {
          "type": "object",
          "properties": {
            "firstName": {
              "type": "string"
            },
            "lastName": {
              "type": "string"
            }
          },
          "required": ["firstName", "lastName"]
        },
        "socialSecurityNumber": {
          "type": ["string", "null"],
          "maxLength": 11
        },
        "businessId": {
          "type": ["string", "null"],
          "maxLength": 9
        },
        "employerIdentifier": {
          "type": ["string", "null"]
        },
        "postalAddress": {
          "type": "object",
          "properties": {
            "addressLine": {
              "type": ["array", "null"],
              "items": {
                "type": ["string", "null"]
              }
            },
            "postalCode": {
              "type": ["string", "null"],
              "maxLength": 5
            },
            "postOffice": {
              "type": ["string", "null"]
            },
            "country": {
              "type": "string",
              "maxLength": 2
            }
          },
          "required": ["country"]
        },
        "number": {
          "type": ["integer", "null"]
        }
      },
      "required": ["bankAccount", "name"]
    },
    "posting": {
      "type": "object",
      "properties": {
        "postingInstallment": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "sum": {
                "type": "number",
                "minimum": 0
              },
              "businessBookkeepingAccount": {
                "type": ["integer", "null"]
              },
              "financeAssessmentAccount": {
                "type": ["integer", "null"]
              },
              "followUpCode1": {
                "type": ["integer", "null"]
              },
              "followUpCode2": {
                "type": ["integer", "null"]
              },
              "partnerCode": {
                "type": ["string", "null"]
              },
              "functionCode": {
                "type": ["string", "null"]
              },
              "ovt": {
                "type": ["string", "null"]
              },
              "operationUnit": {
                "type": ["integer", "null"]
              },
              "projectCode": {
                "type": ["string", "null"]
              },
              "municipalityCode": {
                "type": "string",
                "maxLength": 3
              },
              "vatCode": {
                "type": "string",
                "maxLength": 4
              }
            },
            "required": ["sum", "municipalityCode", "vatCode"]
          }
        },
        "accountsLedgerReceiptType": {
          "type": "string",
          "maxLength": 2
        }
      },
      "required": ["accountsLedgerReceiptType"]
    },
    "view": {
      "type": "object",
      "properties": {
        "type": {
          "type": ["string", "null"]
        },
        "roadName": {
          "type": ["string", "null"]
        },
        "roadId": {
          "type": ["string", "null"]
        },
        "usePriviledgeUnitId": {
          "type": ["string", "null"]
        },
        "municipality": {
          "type": "object",
          "properties": {
            "value": {
              "type": ["string", "null"]
            },
            "code": {
              "type": ["string", "null"],
              "maxLength": 3
            }
          }
        },
        "paymentDecisionRecordNumber": {
          "type": "string"
        },
        "paymentDecisionDate": {
          "type": "string",
          "format": "date"
        },
        "grantDecisionRecordNumber": {
          "type": "string"
        },
        "businessUnit": {
          "type": "object",
          "properties": {
            "value": {
              "type": "string"
            },
            "code": {
              "type": "integer",
              "minimum": 0
            }
          },
          "required": ["value", "code"]
        },
        "creator": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            }
          },
          "required": ["name"]
        },
        "paymentSubjectInspector": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            },
            "email": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                }
              },
              "required": ["value"]
            }
          },
          "required": ["name", "email"]
        },
        "verifyDate": {
          "type": "string",
          "format": "date"
        },
        "paymentPresenter": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            },
            "email": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                }
              },
              "required": ["value"]
            },
            "signedTime": {
              "type": "string",
              "format": "date"
            }
          },
          "required": ["name", "email", "signedTime"]
        },
        "paymentAcceptor": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            },
            "email": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                }
              },
              "required": ["value"]
            },
            "signedTime": {
              "type": "string",
              "format": "date"
            }
          },
          "required": ["name", "email", "signedTime"]
        },
        "additionalInformation": {
          "type": "string"
        },
        "rows": {
          "type": "object",
          "properties": {
            "row": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "grossSum": {
                    "type": "number",
                    "minimum": 0
                  },
                  "vatPercentage": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 100
                  },
                  "vatSum": {
                    "type": "number",
                    "minimum": 0
                  },
                  "netSum": {
                    "type": "number",
                    "minimum": 0
                  }
                },
                "required": ["description", "grossSum", "vatPercentage", "vatSum", "netSum"]
              }
            }
          },
          "required": ["row"]
        },
        "vatSum": {
          "type": "number",
          "minimum": 0
        },
        "netSum": {
          "type": "number",
          "minimum": 0
        },
        "aidType": {
          "type": "string"
        },
        "language": {
          "type": "integer"
        }
      },
      "required": [
        "paymentDecisionRecordNumber",
        "paymentDecisionDate",
        "grantDecisionRecordNumber",
        "verifyDate",
        "businessUnit",
        "additionalInformation",
        "vatSum",
        "netSum",
        "aidType",
        "language"
      ]
    },
    "version": {
      "type": ["string", "null"]
    },
    "claimType": {
      "type": "string"
    },
    "auraAccount": {
      "type": "string"
    },
    "sectorIdentifier": {
      "type": "string"
    },
    "serviceProviderSectorIdentifier": {
      "type": ["string", "null"]
    },
    "participantHomeMunicipality": {
      "type": ["string", "null"],
      "maxLength": 3
    },
    "recipientMunicipality": {
      "type": "string",
      "maxLength": 3
    },
    "employmentMunicipality": {
      "type": ["string", "null"],
      "maxLength": 3
    },
    "payerBusinessId": {
      "type": ["string", "null"],
      "maxLength": 9
    },
    "acculturingStatus": {
      "type": ["boolean", "null"]
    },
    "contractAcculturingStatus": {
      "type": ["boolean", "null"]
    },
    "originalInvoiceNumber": {
      "type": ["string", "null"]
    },
    "originalBuyerReferenceIdentifier": {
      "type": ["string", "null"]
    },
    "euGlobalizationFundDetails": {
      "type": ["object", "null"],
      "properties": {
        "euGlobalizationFundRows": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "globazationFundCode": {
                "type": "string"
              },
              "municipalityCode": {
                "type": "string",
                "maxLength": 3
              },
              "sum": {
                "type": "number",
                "minimum": 0
              },
              "vatCode": {
                "type": "string",
                "maxLength": 4
              }
            }
          }
        }
      }
    },
    "abruptStructuralChangeDetails": {
      "type": ["object", "null"],
      "properties": {
        "abruptStructuralChangeRows": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "abruptStructuralChangeCode": {
                "type": "string"
              },
              "municipalityCode": {
                "type": "string",
                "maxLength": 3
              },
              "sum": {
                "type": "number",
                "minimum": 0
              },
              "vatCode": {
                "type": "string",
                "maxLength": 4
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "delivery",
    "bizTalkPipe",
    "invoiceNumber",
    "invoiceDate",
    "dueDate",
    "receiptDate",
    "grossSum",
    "currency",
    "ourReference",
    "receiver",
    "posting",
    "view",
    "version",
    "claimType",
    "auraAccount",
    "sectorIdentifier",
    "recipientMunicipality"
  ]
}

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/maksuliikenne_single_data.json
{
    "delivery": {
        "fileName": "YA_p24_091_20241031000002_2_HKK.json",
        "id": 60025900,
        "sentAt": "2024-10-31 00:00:02",
        "from": "YA",
        "to": "RONDO"
    },
    "bizTalkPipe": "automatic",
    "invoiceNumber": 60025900,
    "invoiceDate": "2024-10-30 00:00:00",
    "dueDate": "2024-11-03 00:00:00",
    "receiptDate": "2024-10-30 00:00:00",
    "grossSum": 198,
    "currency": "EUR",
    "ourReference": "Kulukorvaus HKK/24154/2024 maksuerä 1/1",
    "customerBankReference": null,
    "periodStartDate": "2024-09-01 00:00:00",
    "periodEndDate": "2024-09-30 00:00:00",
    "paymentPeriodStartDate": null,
    "paymentPeriodEndDate": null,
    "employeeName": null,
    "customProjectCode": null,
    "receiver": {
        "profitCenterCode": 5086,
        "bankAccount": {
            "value": "FI4439289980006088",
            "bicCode": "SBANFIHH"
        },
        "name": {
            "firstName": "Mari",
            "lastName": "Makkonen"
        },
        "socialSecurityNumber": "060589-236F",
        "businessId": null,
        "postalAddress": {
            "addressLine": [
                "Keskuskatu 1"
            ],
            "postalCode": "00100",
            "postOffice": "Helsinki",
            "country": "FI"
        },
        "number": 90060
    },
    "posting": {
        "postingInstallment": [
            {
                "sum": 198,
                "businessBookkeepingAccount": 82620000,
                "financeAssessmentAccount": 42332305109,
                "followUpCode1": 38025112,
                "followUpCode2": null,
                "partnerCode": null,
                "functionCode": null,
                "ovt": null,
                "operationUnit": 3800114101,
                "projectCode": "5086YA0045",
                "municipalityCode": "091",
                "vatCode": "0000",
                "acculturingStatus": null
            }
        ],
        "accountsLedgerReceiptType": "YA"
    },
    "view": {
        "type": "Harkinnanvarainen kulukorvaus",
        "roadName": "5086YA0045",
        "roadId": null,
        "usePriviledgeUnitId": null,
        "municipality": {
            "value": "Helsinki",
            "code": "091"
        },
        "paymentDecisionRecordNumber": "HKK/24154/2024",
        "paymentDecisionDate": "2024-10-30 00:00:00",
        "grantDecisionRecordNumber": "HKK/24154/2024",
        "businessUnit": {
            "value": "HELSINGIN KAUPUNKI",
            "code": 91
        },
        "creator": {
            "name": {
                "firstName": "Maija",
                "lastName": "Maijanen"
            }
        },
        "paymentSubjectInspector": {
            "name": {
                "firstName": "Maija",
                "lastName": "Maijanen"
            },
            "email": {
                "value": "Maija.Maijanen@testi.fi"
            }
        },
        "verifyDate": "2024-10-30 13:48:44",
        "paymentPresenter": {
            "name": {
                "firstName": "Maija",
                "lastName": "Maijanen"
            },
            "email": {
                "value": "Maija.Maijanen@testi.fi"
            },
            "phoneNumber": "-",
            "signedTime": "2024-10-30 13:48:51"
        },
        "paymentAcceptor": {
            "name": {
                "firstName": "Maija",
                "lastName": "Maijanen"
            },
            "email": {
                "value": "Maija.Maijanen@testi.fi"
            },
            "phoneNumber": null,
            "signedTime": "2024-10-30 13:48:48"
        },
        "additionalInformation": "Harkinnanvaraiset kulukorvaukset: 5086YA0045. Myöntöpäätös: 30.10.2024. 5555.",
        "rows": {
            "row": [
                {
                    "description": "Harkinnanvarainen kulukorvaus",
                    "grossSum": 198,
                    "vatPercentage": 0,
                    "vatSum": 0,
                    "netSum": 198
                }
            ]
        },
        "vatSum": 0,
        "netSum": 198,
        "aidType": "00",
        "language": 1
    },
    "version": "2.3",
    "claimType": "HARKINNANVARAINEN_KULUKORVAUS",
    "auraAccount": "4739",
    "sectorIdentifier": "S.14",
    "participantHomeMunicipality": "091",
    "recipientMunicipality": "091",
    "employmentMunicipality": "091",
    "payerBusinessId": "0201256-6",
    "acculturingStatus": false
}

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/kirjanpito_data_tojt.json
{"delivery":{"fileName":"YA_p24_091_20241031100100_0_TOJT.json","id":60025917,"sentAt":"2024-10-31 10:01:00","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025917,"invoiceDate":"2024-10-31 00:00:00","dueDate":"2024-11-03 00:00:00","receiptDate":"2024-10-31 00:00:00","grossSum":1255.0,"currency":"EUR","ourReference":"Hakemus työolosuhteiden järjestelytuesta TOJT/24170/2024 maksuerä 1/1","customerBankReference":null,"periodStartDate":"2024-10-31 00:00:00","periodEndDate":"2024-12-31 00:00:00","paymentPeriodStartDate":"2024-10-01 00:00:00","paymentPeriodEndDate":"2024-10-31 00:00:00","employeeName":null,"customProjectCode":null,"receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI3952900240167500","bicCode":"OKOYFIHH"},"name":{"firstName":"Testifirma OY","lastName":""},"socialSecurityNumber":null,"businessId":"8262500-3","postalAddress":{"addressLine":["Testikatu 1"],"postalCode":"00100","postOffice":"Helsinki","country":"FI"},"number":90060},"posting":{"postingInstallment":[{"sum":1255.0,"businessBookkeepingAccount":82310000,"financeAssessmentAccount":42332305109,"followUpCode1":38025110,"followUpCode2":null,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":3800114101,"projectCode":"5086YA0056","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Työolosuhteiden järjestelytuki","roadName":"5086YA0056","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"TOJT/24170/2024","paymentDecisionDate":"2024-10-31 00:00:00","grantDecisionRecordNumber":"TOJT/24170/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Emilia","lastName":"Kujala"}},"paymentSubjectInspector":{"name":{"firstName":"Emilia","lastName":"Kujala"},"email":{"value":"emilia.kujala@ely-keskus.fi"}},"verifyDate":"2024-10-31 09:59:26","paymentPresenter":{"name":{"firstName":"Emilia","lastName":"Kujala"},"email":{"value":"emilia.kujala@ely-keskus.fi"},"phoneNumber":"-","signedTime":"2024-10-31 09:59:15"},"paymentAcceptor":{"name":{"firstName":"Mari","lastName":"Voutilainen"},"email":{"value":"mari.voutilainen@ely-keskus.fi"},"phoneNumber":null,"signedTime":"2024-10-31 10:00:06"},"additionalInformation":"Työolosuhteiden järjestelytukihakemuksen tuki: 5086YA0056. Myöntöpäätös: 31.10.2024. 5555. Kustannuksia haettu 01.10.2024 - 31.10.2024.","rows":{"row":[{"description":"Työolosuhteiden järjestelytuki","grossSum":1255.0,"vatPercentage":0,"vatSum":0,"netSum":1255.0}]},"vatSum":0,"netSum":1255.0,"aidType":"99","language":1},"version":"2.3","claimType":"TYOOLOSUHTEIDEN_JARJESTELYTUKI","auraAccount":"4300","sectorIdentifier":"S.11","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false}

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/starttiraha/starttiraha_data_uusi.json
{
  "delivery": {
    "fileName": "YA_p22_399_20240820110559_1_SR.json",
    "id": 60025839,
    "sentAt": "2024-09-16 16:17:59",
    "from": "YA",
    "to": "RONDO"
  },
  "bizTalkPipe": "automatic",
  "invoiceNumber": 60025839,
  "refundedInvoiceNumber": 60022742,
  "invoiceDate": "2024-09-16 00:00:00",
  "dueDate": "2024-09-16 00:00:00",
  "receiptDate": "2024-09-16 00:00:00",
  "grossSum": 669.78,
  "currency": "EUR",
  "ourReference": "Starttirahahakemus SR/938/2022 maksuerä 2/8",
  "customerBankReference": null,
  "periodStartDate": "2024-09-16 00:00:00",
  "periodEndDate": "2024-09-16 00:00:00",
  "paymentPeriodStartDate": "2024-09-16 00:00:00",
  "paymentPeriodEndDate": "2024-09-16 00:00:00",
  "employeeName": null,
  "customProjectCode": null,
  "receiver": {
    "profitCenterCode": 111,
    "bankAccount": {
      "value": "FI3040244380000352",
      "bicCode": "OKOYFIHH"
    },
    "name": {
      "firstName": "Jarno",
      "lastName": "Jarno"
    },
    "socialSecurityNumber": "010101+0101",
    "businessId": null,
  "employerIdentifier": null,
    "postalAddress": {
      "addressLine": [
        "Val"
      ],
      "postalCode": "33100",
      "postOffice": "Tampere",
      "country": "FI"
    },
    "number": 90060
  },
  "posting": {
    "postingInstallment": [
      {
        "sum": 669.78,
        "businessBookkeepingAccount": 82620000,
        "financeAssessmentAccount": 42332305106,
        "followUpCode1": null,
        "followUpCode2": null,
        "partnerCode": null,
        "functionCode": null,
        "ovt": "00372296962122",
        "operationUnit": 3800222901,
        "projectCode": "111YA0034",
        "municipalityCode": "399",
        "vatCode": "0000"
      }
    ],
    "accountsLedgerReceiptType": "YA"
  },
  "view": {
    "type": "Yksityistieavustus",
    "roadName": "111YA0034",
    "roadId": null,
    "usePriviledgeUnitId": null,
    "municipality": {
      "value": "Laihia",
      "code": "399"
    },
    "paymentDecisionRecordNumber": "SR/938/2022",
    "paymentDecisionDate": "2024-09-16 00:00:00",
    "grantDecisionRecordNumber": "SR/938/2022",
    "businessUnit": {
      "value": "POHJANMAAN TE-TOIMISTO",
      "code": 1021
    },
    "creator": {
      "name": {
        "firstName": "A006571",
        "lastName": "Heidi"
      }
    },
    "paymentSubjectInspector": {
      "name": {
        "firstName": "A006571",
        "lastName": "Heidi"
      },
      "email": {
        "value": "esimerkki@example.com"
      }
    },
    "verifyDate": "2024-09-16 15:44:07",
    "paymentPresenter": {
      "name": {
        "firstName": "A006571",
        "lastName": "Heidi"
      },
      "email": {
        "value": "esimerkki@example.com"
      },
      "signedTime": "2024-09-16 15:45:07"
    },
    "paymentAcceptor": {
      "name": {
        "firstName": "A006571",
        "lastName": "Heidi"
      },
      "email": {
        "value": "esimerkki@example.com"
      },
      "signedTime": "2024-09-16 15:44:07"
    },
    "additionalInformation": "Starttirahahakemus: 111YA0034. Myöntöpäätös: 26.07.2024. 32305106. Kustannuksia haettu 01.06.2024 - 30.06.2024.",
    "rows": {
      "row": [
        {
          "description": "YA valtionapu erä  2-2024",
          "grossSum": 669.78,
          "vatPercentage": 0,
          "vatSum": 0,
          "netSum": 669.78
        }
      ]
    },
    "vatSum": 0,
    "netSum": 669.78,
    "aidType": "99",
    "language": 1
  },
  "version": "2.1",
  "claimType": "STARTTIRAHA",
  "auraAccount": "4730",
  "sectorIdentifier": "S.14",
  "participantHomeMunicipality": "399",
  "recipientMunicipality": "399",
  "employmentMunicipality": "399",
  "payerBusinessId": "2296962-1",
  "acculturingStatus": true,
  "contractAcculturingStatus": null,
     "originalInvoiceNumber": null,
     "originalBuyerReferenceIdentifier": null,
 "euGlobalizationFundDetails": {
     "euGlobalizationFundRows": [
      {
        "globazationFundCode": "G21310",
        "municipalityCode": "399",
        "sum": 669.78,
        "vatCode": "0000"
      }
    ]
  }
}

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/kirjanpito_data_pt.json
{"delivery":{"fileName":"YA_p24_091_20241031115100_0_PT.json","id":60025925,"sentAt":"2024-10-31 11:51:00","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025925,"invoiceDate":"2024-10-31 00:00:00","dueDate":"2024-11-02 00:00:00","receiptDate":"2024-10-31 00:00:00","grossSum":1250.0,"currency":"EUR","ourReference":"Palkkatuki PT/24172/2024","customerBankReference":"12 34561","periodStartDate":"2024-07-01 00:00:00","periodEndDate":"2024-10-31 00:00:00","paymentPeriodStartDate":"2024-09-01 00:00:00","paymentPeriodEndDate":"2024-09-30 00:00:00","employeeName":"Seppo Sepomäkinen","customProjectCode":"12345","receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI3952900240167500","bicCode":"OKOYFIHH"},"name":{"firstName":"Helsingin kuppi","lastName":""},"socialSecurityNumber":"210218-265B","businessId":"6631305-0","postalAddress":{"addressLine":["Testikatu 1"],"postalCode":"00100","postOffice":"Helsinki","country":"FI"},"number":90055},"posting":{"postingInstallment":[{"sum":1250.0,"businessBookkeepingAccount":82310000,"financeAssessmentAccount":202402024,"followUpCode1":null,"followUpCode2":38099272,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":1,"projectCode":"5086YA0058","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Palkkatukihakemuksen tuki","roadName":"5086YA0058","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"PT/24172/2024","paymentDecisionDate":"2024-10-31 00:00:00","grantDecisionRecordNumber":"PT/24172/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Emma","lastName":"Virtanen"}},"paymentSubjectInspector":{"name":{"firstName":"Emma","lastName":"Virtanen"},"email":{"value":"Emma.Virtanen@email.com"}},"verifyDate":"2024-10-31 11:50:40","paymentPresenter":{"name":{"firstName":"Emma","lastName":"Virtanen"},"email":{"value":"Emma.Virtanen@email.com"},"phoneNumber":"-","signedTime":"2024-10-31 11:47:10"},"paymentAcceptor":{"name":{"firstName":"Emma","lastName":"Virtanen"},"email":{"value":"Emma.Virtanen@email.com"},"phoneNumber":null,"signedTime":"2024-10-31 11:50:47"},"additionalInformation":"Palkkatukihakemuksen tuki: 5086YA0058. Myöntöpäätös: 31.10.2024. 202402024/2024. Kustannuksia haettu 01.09.2024 - 30.09.2024.","rows":{"row":[{"description":"Palkkatukihakemuksen tuki erä 3-2024","grossSum":1250.0,"vatPercentage":0,"vatSum":0,"netSum":1250.0}]},"vatSum":0,"netSum":1250.0,"aidType":"6T","language":1},"version":"2.3","claimType":"PALKKATUKI","auraAccount":"4746","sectorIdentifier":"S.11","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false}
