=== City-of-Helsinki/ya-integration/src/main/resources/schema/kipa/json_schema_MYK_HKK.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "delivery": {
      "type": "object",
      "properties": {
        "fileName": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "minimum": 0
        },
        "sentAt": {
          "type": "string",
          "format": "date"
        },
        "from": {
          "type": "string",
          "maxLength": 2
        },
        "to": {
          "type": "string"
        }
      },
      "required": ["fileName", "id", "sentAt", "from", "to"]
    },
    "bizTalkPipe": {
      "type": "string"
    },
    "invoiceNumber": {
      "type": "integer",
      "minimum": 0
    },
    "refundedInvoiceNumber": {
      "type": ["integer", "null"]
    },
    "invoiceDate": {
      "type": "string",
      "format": "date"
    },
    "dueDate": {
      "type": "string",
      "format": "date"
    },
    "receiptDate": {
      "type": "string",
      "format": "date"
    },
    "grossSum": {
      "type": "number",
      "minimum": 0
    },
    "currency": {
      "type": "string",
      "maxLength": 3
    },
    "ourReference": {
      "type": "string"
    },
    "customerBankReference": {
      "type": ["string", "null"]
    },
    "periodStartDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "periodEndDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "paymentPeriodStartDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "paymentPeriodEndDate": {
      "type": ["string", "null"],
      "format": "date"
    },
    "employeeName": {
      "type": ["string", "null"]
    },
    "customProjectCode": {
      "type": ["string", "null"]
    },
    "receiver": {
      "type": "object",
      "properties": {
        "profitCenterCode": {
          "type": ["integer", "null"]
        },
        "bankAccount": {
          "type": "object",
          "properties": {
            "value": {
              "type": "string",
              "maxLength": 34
            },
            "bicCode": {
              "type": "string",
              "maxLength": 11
            }
          },
          "required": ["value", "bicCode"]
        },
        "name": {
          "type": "object",
          "properties": {
            "firstName": {
              "type": "string"
            },
            "lastName": {
              "type": "string"
            }
          },
          "required": ["firstName", "lastName"]
        },
        "socialSecurityNumber": {
          "type": ["string", "null"],
          "maxLength": 11
        },
        "businessId": {
          "type": ["string", "null"],
          "maxLength": 9
        },
        "employerIdentifier": {
          "type": ["string", "null"]
        },
        "postalAddress": {
          "type": "object",
          "properties": {
            "addressLine": {
              "type": ["array", "null"],
              "items": {
                "type": ["string", "null"]
              }
            },
            "postalCode": {
              "type": ["string", "null"],
              "maxLength": 5
            },
            "postOffice": {
              "type": ["string", "null"]
            },
            "country": {
              "type": "string",
              "maxLength": 2
            }
          },
          "required": ["country"]
        },
        "number": {
          "type": ["integer", "null"]
        }
      },
      "required": ["bankAccount", "name"]
    },
    "posting": {
      "type": "object",
      "properties": {
        "postingInstallment": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "sum": {
                "type": "number",
                "minimum": 0
              },
              "businessBookkeepingAccount": {
                "type": ["integer", "null"]
              },
              "financeAssessmentAccount": {
                "type": ["integer", "null"]
              },
              "followUpCode1": {
                "type": ["integer", "null"]
              },
              "followUpCode2": {
                "type": ["integer", "null"]
              },
              "partnerCode": {
                "type": ["string", "null"]
              },
              "functionCode": {
                "type": ["string", "null"]
              },
              "ovt": {
                "type": ["string", "null"]
              },
              "operationUnit": {
                "type": ["integer", "null"]
              },
              "projectCode": {
                "type": ["string", "null"]
              },
              "municipalityCode": {
                "type": "string",
                "maxLength": 3
              },
              "vatCode": {
                "type": "string",
                "maxLength": 4
              }
            },
            "required": ["sum", "municipalityCode", "vatCode"]
          }
        },
        "accountsLedgerReceiptType": {
          "type": "string",
          "maxLength": 2
        }
      },
      "required": ["accountsLedgerReceiptType"]
    },
    "view": {
      "type": "object",
      "properties": {
        "type": {
          "type": ["string", "null"]
        },
        "roadName": {
          "type": ["string", "null"]
        },
        "roadId": {
          "type": ["string", "null"]
        },
        "usePriviledgeUnitId": {
          "type": ["string", "null"]
        },
        "municipality": {
          "type": "object",
          "properties": {
            "value": {
              "type": ["string", "null"]
            },
            "code": {
              "type": ["string", "null"],
              "maxLength": 3
            }
          }
        },
        "paymentDecisionRecordNumber": {
          "type": "string"
        },
        "paymentDecisionDate": {
          "type": "string",
          "format": "date"
        },
        "grantDecisionRecordNumber": {
          "type": "string"
        },
        "businessUnit": {
          "type": "object",
          "properties": {
            "value": {
              "type": "string"
            },
            "code": {
              "type": "integer",
              "minimum": 0
            }
          },
          "required": ["value", "code"]
        },
        "creator": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            }
          },
          "required": ["name"]
        },
        "paymentSubjectInspector": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            },
            "email": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                }
              },
              "required": ["value"]
            }
          },
          "required": ["name", "email"]
        },
        "verifyDate": {
          "type": "string",
          "format": "date"
        },
        "paymentPresenter": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            },
            "email": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                }
              },
              "required": ["value"]
            },
            "signedTime": {
              "type": "string",
              "format": "date"
            }
          },
          "required": ["name", "email", "signedTime"]
        },
        "paymentAcceptor": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                }
              },
              "required": ["firstName", "lastName"]
            },
            "email": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                }
              },
              "required": ["value"]
            },
            "signedTime": {
              "type": "string",
              "format": "date"
            }
          },
          "required": ["name", "email", "signedTime"]
        },
        "additionalInformation": {
          "type": "string"
        },
        "rows": {
          "type": "object",
          "properties": {
            "row": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "grossSum": {
                    "type": "number",
                    "minimum": 0
                  },
                  "vatPercentage": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 100
                  },
                  "vatSum": {
                    "type": "number",
                    "minimum": 0
                  },
                  "netSum": {
                    "type": "number",
                    "minimum": 0
                  }
                },
                "required": ["description", "grossSum", "vatPercentage", "vatSum", "netSum"]
              }
            }
          },
          "required": ["row"]
        },
        "vatSum": {
          "type": "number",
          "minimum": 0
        },
        "netSum": {
          "type": "number",
          "minimum": 0
        },
        "aidType": {
          "type": "string"
        },
        "language": {
          "type": "integer"
        }
      },
      "required": [
        "paymentDecisionRecordNumber",
        "paymentDecisionDate",
        "grantDecisionRecordNumber",
        "verifyDate",
        "businessUnit",
        "additionalInformation",
        "vatSum",
        "netSum",
        "aidType",
        "language"
      ]
    },
    "version": {
      "type": ["string", "null"]
    },
    "claimType": {
      "type": "string"
    },
    "auraAccount": {
      "type": "string"
    },
    "sectorIdentifier": {
      "type": "string"
    },
    "serviceProviderSectorIdentifier": {
      "type": ["string", "null"]
    },
    "participantHomeMunicipality": {
      "type": ["string", "null"],
      "maxLength": 3
    },
    "recipientMunicipality": {
      "type": "string",
      "maxLength": 3
    },
    "employmentMunicipality": {
      "type": ["string", "null"],
      "maxLength": 3
    },
    "payerBusinessId": {
      "type": ["string", "null"],
      "maxLength": 9
    },
    "acculturingStatus": {
      "type": ["boolean", "null"]
    },
    "contractAcculturingStatus": {
      "type": ["boolean", "null"]
    },
    "originalInvoiceNumber": {
      "type": ["string", "null"]
    },
    "originalBuyerReferenceIdentifier": {
      "type": ["string", "null"]
    },
    "euGlobalizationFundDetails": {
      "type": ["object", "null"],
      "properties": {
        "euGlobalizationFundRows": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "globazationFundCode": {
                "type": "string"
              },
              "municipalityCode": {
                "type": "string",
                "maxLength": 3
              },
              "sum": {
                "type": "number",
                "minimum": 0
              },
              "vatCode": {
                "type": "string",
                "maxLength": 4
              }
            }
          }
        }
      }
    },
    "abruptStructuralChangeDetails": {
      "type": ["object", "null"],
      "properties": {
        "abruptStructuralChangeRows": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "abruptStructuralChangeCode": {
                "type": "string"
              },
              "municipalityCode": {
                "type": "string",
                "maxLength": 3
              },
              "sum": {
                "type": "number",
                "minimum": 0
              },
              "vatCode": {
                "type": "string",
                "maxLength": 4
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "delivery",
    "bizTalkPipe",
    "invoiceNumber",
    "invoiceDate",
    "dueDate",
    "receiptDate",
    "grossSum",
    "currency",
    "ourReference",
    "receiver",
    "posting",
    "view",
    "version",
    "claimType",
    "auraAccount",
    "sectorIdentifier",
    "recipientMunicipality"
  ]
}

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/kirjanpito_data_hkk.json
{"delivery":{"fileName":"YA_p24_091_20241031000005_12_HKK.json","id":60025912,"sentAt":"2024-10-31 00:00:05","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025912,"invoiceDate":"2024-10-30 00:00:00","dueDate":"2024-11-03 00:00:00","receiptDate":"2024-10-30 00:00:00","grossSum":198.0,"currency":"EUR","ourReference":"Kulukorvaus HKK/24165/2024 maksuerä 1/1","customerBankReference":null,"periodStartDate":"2024-09-01 00:00:00","periodEndDate":"2024-09-30 00:00:00","paymentPeriodStartDate":null,"paymentPeriodEndDate":null,"employeeName":null,"customProjectCode":null,"receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI7447424428000621","bicCode":"POPFFI22"},"name":{"firstName":"Maija","lastName":"Mehiläinen"},"socialSecurityNumber":"090884-772U","businessId":null,"postalAddress":{"addressLine":["Luopatie 8"],"postalCode":"02310","postOffice":"Helsinki","country":"FI"},"number":90060},"posting":{"postingInstallment":[{"sum":198.0,"businessBookkeepingAccount":82620000,"financeAssessmentAccount":42332305109,"followUpCode1":38025112,"followUpCode2":null,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":3800114101,"projectCode":"5086YA0053","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Harkinnanvarainen kulukorvaus","roadName":"5086YA0053","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"HKK/24165/2024","paymentDecisionDate":"2024-10-30 00:00:00","grantDecisionRecordNumber":"HKK/24165/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Maija","lastName":"Mäkelä"}},"paymentSubjectInspector":{"name":{"firstName":"Maija","lastName":"Mäkelä"},"email":{"value":"Maija.Mäkelä@email.com"}},"verifyDate":"2024-10-30 15:15:39","paymentPresenter":{"name":{"firstName":"Maija","lastName":"Mäkelä"},"email":{"value":"Maija.Mäkelä@email.com"},"phoneNumber":"-","signedTime":"2024-10-30 15:15:44"},"paymentAcceptor":{"name":{"firstName":"Maija","lastName":"Mäkelä"},"email":{"value":"Maija.Mäkelä@email.com"},"phoneNumber":null,"signedTime":"2024-10-30 15:15:42"},"additionalInformation":"Harkinnanvaraiset kulukorvaukset: 5086YA0053. Myöntöpäätös: 30.10.2024. 5555.","rows":{"row":[{"description":"Harkinnanvarainen kulukorvaus","grossSum":198.0,"vatPercentage":0,"vatSum":0,"netSum":198.0}]},"vatSum":0,"netSum":198.0,"aidType":"00","language":1},"version":"2.3","claimType":"HARKINNANVARAINEN_KULUKORVAUS","auraAccount":"4739","sectorIdentifier":"S.14","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false}

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/maksuliikenne_data.json
[{"delivery":{"fileName":"YA_p24_091_20241031000002_2_HKK.json","id":60025900,"sentAt":"2024-10-31 00:00:02","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025900,"invoiceDate":"2024-10-30 00:00:00","dueDate":"2024-11-03 00:00:00","receiptDate":"2024-10-30 00:00:00","grossSum":198.0,"currency":"EUR","ourReference":"Kulukorvaus HKK/24154/2024 maksuerä 1/1","customerBankReference":null,"periodStartDate":"2024-09-01 00:00:00","periodEndDate":"2024-09-30 00:00:00","paymentPeriodStartDate":null,"paymentPeriodEndDate":null,"employeeName":null,"customProjectCode":null,"receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI4439289980006088","bicCode":"SBANFIHH"},"name":{"firstName":"Mari","lastName":"Makkonen"},"socialSecurityNumber":"060589-236F","businessId":null,"postalAddress":{"addressLine":["Keskuskatu 1"],"postalCode":"00100","postOffice":"Helsinki","country":"FI"},"number":90060},"posting":{"postingInstallment":[{"sum":198.0,"businessBookkeepingAccount":82620000,"financeAssessmentAccount":42332305109,"followUpCode1":38025112,"followUpCode2":null,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":3800114101,"projectCode":"5086YA0045","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Harkinnanvarainen kulukorvaus","roadName":"5086YA0045","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"HKK/24154/2024","paymentDecisionDate":"2024-10-30 00:00:00","grantDecisionRecordNumber":"HKK/24154/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Maija","lastName":"Maijanen"}},"paymentSubjectInspector":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"}},"verifyDate":"2024-10-30 13:48:44","paymentPresenter":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"},"phoneNumber":"-","signedTime":"2024-10-30 13:48:51"},"paymentAcceptor":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"},"phoneNumber":null,"signedTime":"2024-10-30 13:48:48"},"additionalInformation":"Harkinnanvaraiset kulukorvaukset: 5086YA0045. Myöntöpäätös: 30.10.2024. 5555.","rows":{"row":[{"description":"Harkinnanvarainen kulukorvaus","grossSum":198.0,"vatPercentage":0,"vatSum":0,"netSum":198.0}]},"vatSum":0,"netSum":198.0,"aidType":"00","language":1},"version":"2.3","claimType":"HARKINNANVARAINEN_KULUKORVAUS","auraAccount":"4739","sectorIdentifier":"S.14","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false},{"delivery":{"fileName":"YA_p24_091_20241031000001_0_MYK.json","id":60025897,"sentAt":"2024-10-31 00:00:01","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025897,"invoiceDate":"2024-10-30 00:00:00","dueDate":"2024-11-03 00:00:00","receiptDate":"2024-10-30 00:00:00","grossSum":115.25,"currency":"EUR","ourReference":"Matka- ja yöpymiskustannusten korvaus MYK/24150/2024 maksuerä 1/1","customerBankReference":null,"periodStartDate":"2024-10-01 00:00:00","periodEndDate":"2024-10-02 00:00:00","paymentPeriodStartDate":null,"paymentPeriodEndDate":null,"employeeName":null,"customProjectCode":null,"receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI0280001800223340","bicCode":"DABAFIHH"},"name":{"firstName":"Ville","lastName":"Villinen"},"socialSecurityNumber":"210694-433L","businessId":null,"postalAddress":{"addressLine":["Testikatu 1"],"postalCode":"00100","postOffice":"Helsinki","country":"FI"},"number":90060},"posting":{"postingInstallment":[{"sum":115.25,"businessBookkeepingAccount":82620000,"financeAssessmentAccount":42332305109,"followUpCode1":38025110,"followUpCode2":null,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":3800114101,"projectCode":"5086YA0042","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Matka- ja yöpymiskustannusten korvaus","roadName":"5086YA0042","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"MYK/24150/2024","paymentDecisionDate":"2024-10-30 00:00:00","grantDecisionRecordNumber":"MYK/24150/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Maija","lastName":"Maijanen"}},"paymentSubjectInspector":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"}},"verifyDate":"2024-10-30 12:12:18","paymentPresenter":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"},"phoneNumber":"-","signedTime":"2024-10-30 12:12:18"},"paymentAcceptor":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"},"phoneNumber":null,"signedTime":"2024-10-30 12:12:32"},"additionalInformation":"Matka- ja yöpymiskustannusten korvaus: 5086YA0042. Myöntöpäätös: 30.10.2024. 5555.","rows":{"row":[{"description":"Matka- ja yöpymiskustannusten korvaus","grossSum":115.25,"vatPercentage":0,"vatSum":0,"netSum":115.25}]},"vatSum":0,"netSum":115.25,"aidType":"99","language":1},"version":"2.3","claimType":"MATKA_JA_YOPYMISKUSTANNUSTENKORVAUS","auraAccount":"4739","sectorIdentifier":"S.14","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false},{"delivery":{"fileName":"YA_p24_091_20241031000001_1_MYK.json","id":60025898,"sentAt":"2024-10-31 00:00:01","from":"YA","to":"RONDO"},"bizTalkPipe":"automatic","invoiceNumber":60025898,"invoiceDate":"2024-10-30 00:00:00","dueDate":"2024-11-03 00:00:00","receiptDate":"2024-10-30 00:00:00","grossSum":105.59,"currency":"EUR","ourReference":"Matka- ja yöpymiskustannusten korvaus MYK/24151/2024 maksuerä 1/1","customerBankReference":null,"periodStartDate":"2024-10-01 00:00:00","periodEndDate":"2024-10-02 00:00:00","paymentPeriodStartDate":null,"paymentPeriodEndDate":null,"employeeName":null,"customProjectCode":null,"receiver":{"profitCenterCode":5086,"bankAccount":{"value":"FI0280001800223340","bicCode":"DABAFIHH"},"name":{"firstName":"Kukka","lastName":"Kukkanen"},"socialSecurityNumber":"221253-7613","businessId":null,"postalAddress":{"addressLine":["Testikatu 1"],"postalCode":"00100","postOffice":"Helsinki","country":"FI"},"number":90060},"posting":{"postingInstallment":[{"sum":105.59,"businessBookkeepingAccount":82620000,"financeAssessmentAccount":42332305109,"followUpCode1":38025110,"followUpCode2":null,"partnerCode":null,"functionCode":null,"ovt":null,"operationUnit":3800114101,"projectCode":"5086YA0043","municipalityCode":"091","vatCode":"0000","acculturingStatus":null}],"accountsLedgerReceiptType":"YA"},"view":{"type":"Matka- ja yöpymiskustannusten korvaus","roadName":"5086YA0043","roadId":null,"usePriviledgeUnitId":null,"municipality":{"value":"Helsinki","code":"091"},"paymentDecisionRecordNumber":"MYK/24151/2024","paymentDecisionDate":"2024-10-30 00:00:00","grantDecisionRecordNumber":"MYK/24151/2024","businessUnit":{"value":"HELSINGIN KAUPUNKI","code":91},"creator":{"name":{"firstName":"Maija","lastName":"Maijanen"}},"paymentSubjectInspector":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"}},"verifyDate":"2024-10-30 12:18:00","paymentPresenter":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"},"phoneNumber":"-","signedTime":"2024-10-30 12:18:00"},"paymentAcceptor":{"name":{"firstName":"Maija","lastName":"Maijanen"},"email":{"value":"Maija.Maijanen@testi.fi"},"phoneNumber":null,"signedTime":"2024-10-30 12:18:09"},"additionalInformation":"Matka- ja yöpymiskustannusten korvaus: 5086YA0043. Myöntöpäätös: 30.10.2024. 5555.","rows":{"row":[{"description":"Matka- ja yöpymiskustannusten korvaus","grossSum":105.59,"vatPercentage":0,"vatSum":0,"netSum":105.59}]},"vatSum":0,"netSum":105.59,"aidType":"99","language":1},"version":"2.3","claimType":"MATKA_JA_YOPYMISKUSTANNUSTENKORVAUS","auraAccount":"4739","sectorIdentifier":"S.14","participantHomeMunicipality":"091","recipientMunicipality":"091","employmentMunicipality":"091","payerBusinessId":"0201256-6","acculturingStatus":false}]

=== City-of-Helsinki/ya-integration/src/test/java/fi/integration/ya/resources/maksuliikenne/maksuliikenne_data_uusi.json
{
  "delivery": {
    "fileName": "YA_p24_091_20240820141359_0_PT55.json",
    "id": 60022704,
    "sentAt": "2024-09-16 00:00:00",
    "from": "YA",
    "to": "RONDO"
  },
  "bizTalkPipe": "automatic",
  "invoiceNumber": 60022704,
  "refundedInvoiceNumber": 60022742,
  "invoiceDate": "2024-09-16 00:00:00",
  "dueDate": "2024-09-16 00:00:00",
  "receiptDate": "2024-09-16 00:00:00",
  "grossSum": 1764.00,
  "currency": "EUR",
  "ourReference": "Työllistämistuki PT55/2822/2023",
  "customerBankReference": null,
  "periodStartDate": "2024-09-16 00:00:00",
  "periodEndDate": "2024-09-16 00:00:00",
  "paymentPeriodStartDate": "2024-09-16 00:00:00",
  "paymentPeriodEndDate": "2024-09-16 00:00:00",
  "employeeName": "Matti tai Maija Meikäläinen",
  "customProjectCode": null,
  "receiver": {
    "profitCenterCode": 100,
    "bankAccount": {
      "value": "FI3040244380000352",
      "bicCode": "DABAFIHH"
    },
    "name": {
      "firstName": "Yrityksen tai yhteisön nimi",
      "lastName": ""
    },
    "socialSecurityNumber": "010101+0101",
    "businessId": "1234567-1",
  "employerIdentifier": null,
    "postalAddress": {
      "addressLine": [
        "Man"
      ],
      "postalCode": "33100",
      "postOffice": "Tampere",
      "country": "FI"
    },
    "number": 90060
  },
  "posting": {
    "postingInstallment": [
      {
        "sum": 1764.00,
        "businessBookkeepingAccount": 82620000,
        "financeAssessmentAccount": 3230552,
        "followUpCode1": null,
        "followUpCode2": null,
        "partnerCode": null,
        "functionCode": null,
        "ovt": "00372296962111",
        "operationUnit": 3800261004,
        "projectCode": "100YA0216",
        "municipalityCode": "091",
        "vatCode": "0000"
      }
    ],
    "accountsLedgerReceiptType": "YA"
  },
  "view": {
    "type": "Palkkatukihakemuksen tuki",
    "roadName": "100YA0216",
    "roadId": null,
    "usePriviledgeUnitId": null,
    "municipality": {
      "value": "Helsinki",
      "code": "091"
    },
    "paymentDecisionRecordNumber": "PT55/2822/2023",
    "paymentDecisionDate": "2024-09-16 00:00:00",
    "grantDecisionRecordNumber": "PT55/2822/2023",
    "businessUnit": {
      "value": "UUDENMAAN TE-TOIMISTO",
      "code": 1001
    },
    "creator": {
      "name": {
        "firstName": "A030478",
        "lastName": "Mira"
      }
    },
    "paymentSubjectInspector": {
      "name": {
        "firstName": "A030478",
        "lastName": "Mira"
      },
      "email": {
        "value": "esimerkki@example.com"
      }
    },
    "verifyDate": "2024-09-16 15:44:07",
    "paymentPresenter": {
      "name": {
        "firstName": "A030478",
        "lastName": "Mira"
      },
      "email": {
        "value": "esimerkki@example.com"
      },
      "signedTime": "2024-09-16 15:45:07"
    },
    "paymentAcceptor": {
      "name": {
        "firstName": "A007984",
        "lastName": "Mira"
      },
      "email": {
        "value": "esimerkki@example.com"
      },
      "signedTime": "2024-09-16 15:44:07"
    },
    "additionalInformation": "Hakemus 55 vuotta täyttäneiden työllistämistuesta: 100YA0216. Myöntöpäätös: 17.07.2023. 82620000. Kustannuksia haettu 01.02.2023 - 28.02.2023.",
    "rows": {
      "row": [
        {
          "description": "Palkkatukihakemuksen tuki erä 2-2024",
          "grossSum": 1764.00,
          "vatPercentage": 0,
          "vatSum": 0,
          "netSum": 1764.00
        }
      ]
    },
    "vatSum": 0,
    "netSum": 1764.00,
    "aidType": "55",
    "language": 1
  },
  "version": "2.1",
  "claimType": "PALKKATUKI_55V",
  "auraAccount": "4746",
  "sectorIdentifier": "S.11",
  "serviceProviderSectorIdentifier": null,
  "participantHomeMunicipality": "091",
  "recipientMunicipality": "091",
  "employmentMunicipality": "091",
  "payerBusinessId": "2296962-1",
  "acculturingStatus": true,
  "contractAcculturingStatus": null,
  "originalInvoiceNumber": null,
  "originalBuyerReferenceIdentifier": null,
  "euGlobalizationFundDetails": {
    "euGlobalizationFundRows": [
      {
        "globazationFundCode": "G21310",
        "municipalityCode": "091",
        "sum": 1764.00,
        "vatCode": "0000"
      }
    ]
  },
  "abruptStructuralChangeDetails": {
    "abruptStructuralChangeRows": [
      {
        "abruptStructuralChangeCode": "R01",
        "municipalityCode": "992",
        "sum": 1500.00,
        "vatCode": "0000"
      }
    ]
  }
}
